#!/bin/bash

main() {
  set_globals
  parse_options "$@"

  [[ -z "$CDPATH" ]] && die "Please set your CDPATH variable"

  walk_cd_path
}

set_globals() {
  SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
  # This is the list of git hooks as of 2026-03-05
  HOOK_FILES=$(echo "$SCRIPT_DIR"/{applypatch-msg,commit-msg,fsmonitor-watchman,post-update,pre-applypatch,pre-commit,pre-merge-commit,pre-push,pre-rebase,pre-receive,prepare-commit-msg,push-to-checkout,sendemail-validate,update})
  FORCE=false
}

parse_options() {
  while [[ -n ${1} ]]; do
    case ${1} in
      help | -h | --help)
        usage
        ;;
      -f | --force)
        FORCE=true
        ;;
      *)
        log_error "Unknown option: '$1'"
        usage
        ;;
    esac

    # shellcheck disable=SC2317
    shift
  done
}

usage() {
  log_heading "$(basename "$0")" "Symlinks these git hook scripts to all repos in your CDPATH"
  log ""
  log "Usage:"
  log "${YELLOW}$(basename "$0") [OPTIONS]"
  log "\nOptions:"
  log "${YELLOW}-f,--force     ${CYAN}Forces overwrite of existing hooks"
  #log "${YELLOW}-x,--xxx ARG     ${CYAN}xxx."
  log "${YELLOW}help,-h,--help  ${CYAN}Display this help."
  log ""

  exit
}

walk_cd_path() {
  local dir hook_dir

  echo $CDPATH |
    tr ':' '\n' |
    while read -r dir; do
      if [[ $dir != '.' ]]; then
        log_heading "Checking all git repos under $YELLOW$dir"
        cd $dir || continue
        for hook_dir in */.git/hooks; do
          [[ -d "$hook_dir" ]] && copy_hooks_to_repo "$hook_dir"
        done
      fi
    done
}

copy_hooks_to_repo() {
  local hook_dir="$1" hook_file

  log_debug "Checking $YELLOW$hook_dir"

  for hook_file in $HOOK_FILES; do
    if [[ -e "$hook_file" ]]; then
      copy_hook "$hook_file" "$hook_dir"
    fi
  done
}

copy_hook() {
  local hook_file="$1" hook_dir="$2" target link_target
  target="$hook_dir/$(basename "$hook_file")"

  # Does the hook already exist?
  if [[ -e "$target" ]]; then
    log_debug "$YELLOW$target ${cyan}already exists"

    if [[ -L "$target" ]]; then
      log_debug "$yellow$target ${cyan}is a symlink"
      link_target=$(readlink "$target")
      log_debug "Its target is $yellow$link_target"
      if [[ "$hook_file" == "$link_target" ]]; then
        log_debug "Already linked to this hook."
        return 0
      fi
    else
      log_debug "$yellow$target ${cyan}is not a symlink"
    fi

    if $FORCE; then
      log "${RED}Overwriting $YELLOW$target"
    else
      return 0
    fi
  fi

  # Double dirname so we log the repo,not the .git directory.
  log "Installing $YELLOW$(basename "$hook_file")$CYAN in $YELLOW$(dirname "$(dirname $hook_dir)")..."
  ln -sf "$hook_file" "$hook_dir/$(basename $hook_file)"
}

################################################################################
# Common utility script functions
# This is a common block of code inserted into all my scripts. I choose to do this rather than put them in a
# separate `script_common` file,because having these functions in the same file helps with auto-completion in
# the IDE.
# So ignore any IDE or AI-review warnings about unused functions.
define_colors() {
  # Define some colors:
  black='\x1b[0;30m'
  red='\x1b[0;31m'
  green='\x1b[0;32m'
  yellow='\x1b[0;33m'
  blue='\x1b[0;34m'
  pink='\x1b[0;35m'
  cyan='\x1b[0;36m'
  grey='\x1b[0;37m'
  BLACK='\x1b[1;30m'
  RED='\x1b[1;31m'
  GREEN='\x1b[1;32m'
  YELLOW='\x1b[1;33m'
  BLUE='\x1b[1;34m'
  PINK='\x1b[1;35m'
  CYAN='\x1b[1;36m'
  WHITE='\x1b[1;37m'
  NC='\x1b[0m' # No Color
  CURSOR_UP='\x1b[A'
  CLEAR_LINE='\x1b[K'

  # Add dummy references to each color variable to avoid having to add "shellcheck disable=SC2034" comments on the unused ones.
  echo "$black $red $green $yellow $blue $pink $cyan $grey $BLACK $RED $GREEN $YELLOW $BLUE $PINK $CYAN $WHITE $NC $CURSOR_UP $CLEAR_LINE" > /dev/null
}

install_if_necessary() {
  local command="$1" package="$2" description="$3" ignore

  if ! command -v "$command" >& /dev/null; then
    if ! command -v brew >& /dev/null; then
      log_heading "Installing brew (a utility for installing command line packages)."
      read -rp "Press enter when ready, Ctrl-C to quit: " ignore
      do_or_die /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi

    log_heading "Installing $package ($description)."
    # shellcheck disable=SC2034
    read -rp "Press enter when ready, Ctrl-C to quit: " ignore
    brew update
    do_or_die brew install "$package"
  fi
}

is_mac() {
  [[ $(uname) == "Darwin" ]]
}

is_linux() {
  [[ $(uname) == "Linux" ]]
}

is_wsl() {
  is_linux && [[ -d /mnt/c ]]
}

get_platform() {
  if is_mac; then
    echo mac
  elif is_wsl; then
    echo wsl
  elif is_linux; then
    echo "linux-$(uname -m | sed -e 's/aarch64/arm64/; s/x86_64/amd64/')"
  else
    echo unknown-os
  fi
}

# gdate is gnu date, which supports sub-second resolution
# Install it via `brew install gdate`
if command -v gdate >/dev/null; then
  date_prefix() {
    gdate +%H:%M:%S.%3N
  }
else
  date_prefix() {
    date +%T
  }
fi

log() {
  echo -e "${CYAN}$*$NC" 1>&2
}

log_timestamp() {
  echo -e "$(date_prefix) ${CYAN}$*$NC" 1>&2
}

log_stdout() {
  echo -e "${CYAN}$*$NC"
}

log_heading() {
  local heading="$1" extra="$2" ruler
  # Strip ansi color codes out of the message when creating the ruler
  ruler=$(echo -n "$heading" | sed -e 's/\\x1b\[[0-9;]*m//g' | sed -e 's/./=/g')

  echo -e "$CYAN+=$ruler=+$NC" 1>&2
  echo -e "$CYAN| $heading $CYAN|    $extra$NC" 1>&2
  echo -e "$CYAN+=$ruler=+$NC" 1>&2
}

log_error() {
  echo -e "${RED}$*$NC" 1>&2
}

log_no_newline() {
  echo -en "${CYAN}$*$NC" 1>&2
}

log_debug() {
  [[ -n "$DEBUG" ]] &&
    echo -e "$cyan$*$NC" 1>&2
}

die() {
  log_error "ERROR: $*"
  exit 1
}

do_or_die() {
  "$@" || die "Command failed: '$*'"
}

define_colors
# End of common utility functions
################################################################################

main "$@"
