#!/bin/bash

# This pre-commit hook will check to ensure that:
#
# 1. you're not commiting directly to the default branch.
# 2. none of your staged changes has a "don't commit" comment.
# 3. you're not accidentally checking in secrets in your config files

main() {
  init

  # Check that we're not committing directly into the default branch by mistake.
  check_branch
  
  # Get the list of staged files once, to save invoking the same command over and over again.
  get_staged_files
  
  # Check for "n o c o m m i t" comments. (I am trying to avoid having the actual word in this script, so that
  # if I copy this script to a repo, and I search for that word in my project, I don't get 12 hits from this file).
  check_for_no_commit
  
  # Check rust files for `todo!()`
  check_for_rust_todo
  
  # Ensure we're not accidentally committing any secrets into config files.
  check_for_secrets

  # How to add custom pre-commit logic in your repo:
  #
  # Rather than editing your copy of this file, you can place any custom
  # pre-commit logic for your repo in .git/hooks/pre-commit-extras.
  #
  # The file will be sourced, so the global variables in this
  # file ($STAGED_FILES etc) will be available.
  #
  # Sample pre-commit-extras file:
  #
  # my_extra_hook() {
  #  local staged_file
  #  while read -r staged_file; do
  #    ... your logic here
  #  done < "$STAGED_FILES"
  # }
  #
  # To indicate failure, simply append to the $FAIL_MSGS variable, like this:
  # FAIL_MSGS="${FAIL_MSGS}! ❌ This is a helpful error message!\n"
  run_extra_hooks

  go_no_go
}

init() {
  # Redirect all subsequent stdout to stderr.
  exec 1>&2

  # Git hooks are run from the root of the repo (no matter where you're running the command from).
  # Sanity check:
  if [[ ! -d .git ]]; then
    echo "pre-commit: '.git' directory not found; not being run from a git repo?"
    exit 1
  fi

  # shellcheck disable=SC2034
  REPO_ROOT=$(pwd)
  HOOK_DIR=$(pwd)/.git/hooks
  STAGED_FILES=/tmp/git-staged.$$
  RENAMED_FILES=/tmp/git-renamed.$$
  FAIL_MSGS=

  # This bit of magic is needed so that the script works even in brand new repos, with no previous commits.
  if git rev-parse --verify HEAD > /dev/null 2>&1; then
    AGAINST=HEAD
  else
    # Initial commit: diff against an empty tree object
    # (This is a special value, not random. It's the SHA of the empty-tree).
    AGAINST=4b825dc642cb6eb9a060e54bf8d69288fbee4904
  fi

  # If any command in a pipeline fails, that return code will be used as the return code of the whole pipeline
  set -o pipefail
}

# Check that we're not committing directly into the default branch by mistake.
check_branch() {
  local branch default_branch
  [[ -e "$HOOK_DIR/.commit_to_default_ok" ]] && return

  branch=$(git rev-parse --abbrev-ref $AGAINST)
  default_branch=$(git remote show origin | sed -n '/HEAD branch/s/.*: //p')

  if [[ ${branch} == "$default_branch" ]]; then
    FAIL_MSGS="${FAIL_MSGS}! ❌ Don't commit directly to the '$default_branch' branch!\n"
    FAIL_MSGS="${FAIL_MSGS}!    To disable this: touch .git/hooks/.commit_to_default_ok\n"
  else
    echo "pre-commit: ✅ branch is not the default branch"
  fi
}

# Get the list of staged files once, to save invoking the same command over and over again.
get_staged_files() {
  # Use --name-status rather than --name-only so we can omit renamed and deleted files.
  # Redirect to a tmp file rather than store the output in a variable. This way we can handle filenames with spaces.
  grep -v '^D' <(git diff --cached --name-status ${AGAINST}) | sed -e 's/^.*\t//' > "$STAGED_FILES"
  grep '^R'    <(git diff --cached --name-status ${AGAINST}) | sed -e "s/^R[0-9a-f]*\t//; s/\t/:::/" > "$RENAMED_FILES"

  trap 'cleanup' EXIT INT TERM
}

# Check for "n o c o m m i t" comments (I am trying to avoid having the actual word in this script, so that
# if I copy this script to a repo, and I search for that word in my project, I don't get 12 hits from this file).
# Extremely useful for ensuring that you remove temporary debugging junk that you
# don't want to commit!
#
# TODO jafischer-2024-02-26: assumes stock git diff output; doesn't work if you're using something like
#                            "difftool" for prettier git diffs.
check_for_no_commit() {
  local staged_file renamed_line found special_word="no"
  #
  special_word="${special_word}commit"
  while read -r staged_file; do
    # Skip this script, obviously.
    [[ $(basename "$staged_file") == pre-commit ]] && continue
    # Want to match with don't commit, dont_commit, etc.
    git diff --staged "$staged_file" \
      | grep -v '^[-]' \
      | grep -i "\(^[+].*DON'*T[ _]*COMMIT\)\|\(^[+].*$special_word\)" > /dev/null \
      && {
        FAIL_MSGS="${FAIL_MSGS}! ❌ $staged_file has a $special_word (or \"don't commit\") comment\n"
        found=yes
      }
    done < "$STAGED_FILES"

  while read -r renamed_line; do
    local old_name=${renamed_line/:::*} new_name=${renamed_line/*:::}
    # Skip this script, obviously.
    [[ $(basename "$new_name") == pre-commit ]] && continue

    # For renamed files, we only want to look at the changes, not the entire file; so diff the old and the new.
    git diff HEAD^ HEAD -M -- "$old_name" "$new_name" \
      | grep -i "\(^[+].*DON'*T[ _]*COMMIT\)\|\(^[+].*$special_word\)" > /dev/null \
      && {
        FAIL_MSGS="${FAIL_MSGS}! ❌ $new_name has a $special_word (or \"don't commit\") comment\n"
        found=yes
      }
  done < "$RENAMED_FILES"

  if [[ -z $found ]]; then
    echo "pre-commit: ✅ No '$special_word' comments"
  fi
}

check_for_rust_todo() {
  local staged_file todo_found rust_found

  while read -r staged_file; do
    if [[ "$staged_file" == *".rs" ]]; then
      rust_found=1
      git diff --staged "$staged_file" \
        | grep -v '^[-]' \
        | grep -E '\<todo\>!()' > /dev/null \
        && {
          FAIL_MSGS="${FAIL_MSGS}! ❌ $staged_file has a todo!() statement\n"
          todo_found=1
        }
    fi
  done < "$STAGED_FILES"

  if [[ -z $todo_found ]] && [[ -n $rust_found ]]; then
    echo "pre-commit: ✅ No 'todo!()' statements"
  fi
}

# Ensure we're not accidentally committing any secrets. Just a simple-minded grep for certain keywords like password,
# privateKey, etc.
check_for_secrets() {
  local staged_file renamed_line ext fail_msg secrets_found
  while read -r staged_file; do
    ext=${staged_file##*.}
    if [[ ${ext} == "properties" || ${ext} == "yml" || ${ext} == "yaml"  || ${ext} == "json" ]]; then
      fail_msg=$(git diff --staged "$staged_file" | check_diffs_for_secrets "$staged_file")
      if [[ -n $fail_msg ]]; then
        FAIL_MSGS="${FAIL_MSGS}${fail_msg}"
        secrets_found=yes
      fi
    fi
  done < "$STAGED_FILES"
  while read -r renamed_line; do
    # Split old_name:::new_name into old_name and new_name.
    local old_name=${renamed_line/:::*} new_name=${renamed_line/*:::}
    ext=${new_name##*.}
    if [[ ${ext} == "properties" || ${ext} == "yml" || ${ext} == "yaml"  || ${ext} == "json" ]]; then
      fail_msg=$(git diff HEAD^ HEAD -M -- "$old_name" "$new_name" | check_diffs_for_secrets "$new_name")
      if [[ -n $fail_msg ]]; then
        FAIL_MSGS="${FAIL_MSGS}${fail_msg}"
        secrets_found=yes
      fi
    fi
  done < "$RENAMED_FILES"

  if [[ -z $secrets_found ]]; then
    echo "pre-commit: ✅ no secrets in property/config files"
  fi
}

check_diffs_for_secrets() {
  local file="$*" grep_output

  if grep_output=$(grep -v "^-" \
    | grep -iv "\(supersecret\)\|\(ENC(\)\|\(app.encryption.password\)\|\(secretRef:\)" \
    | grep -i "\(secret.*[:=]\)\|\(privatekey.*[:=]\)\|\(password.*[:=]\)")
  then
    if ! grep -i "^$file\$" "$HOOK_DIR/.secretsok" > /dev/null 2>&1; then
      # shellcheck disable=SC2001
      echo -e "! ❌ $file appears to contain secrets:\n $(echo "$grep_output" | sed -e 's/^/    /')"
      echo -e "!    To disable checking this file for secrets:"
      echo -e "!    echo $file >> .git/hooks/.secretsok\\\\n"
    fi
  fi
}

run_extra_hooks() {
  [[ -e "$HOOK_DIR/pre-commit-extras" ]] || return 0

  echo "pre-commit: running pre-commit-extras"
  source "$HOOK_DIR/pre-commit-extras"
}

die() {
  echo "ERROR: $*"
  exit 1
}

do_or_die() {
  "$@" || die "Command failed: '$*'"
}

go_no_go() {
  # Did we fail any checks?
  if [[ -n ${FAIL_MSGS} ]]; then
    echo -e "!\n!\n! PRE-COMMIT CHECK(S) FAILED:"
    echo -en "!\n!\n${FAIL_MSGS}"
    echo -e "!\n! [use 'git commit --no-verify' to commit anyway]"
    echo -e "! [Remember that if you fix something, you need to stage the fix via 'git add' before committing again]"
    exit 1
  fi

  echo "pre-commit: ✅ All tests pass!"
}

cleanup() {
  rm "$STAGED_FILES" >& /dev/null
  rm "$RENAMED_FILES" >& /dev/null
}

main
